In [1]:
import torch

## squeeze

In [2]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [3]:
print(ft.squeeze())

tensor([0., 1., 2.])


In [4]:
print(ft.squeeze().shape)

torch.Size([3])


In [5]:
display(ft.squeeze(dim = 0))
display(ft.squeeze(dim = 1))

tensor([[0.],
        [1.],
        [2.]])

tensor([0., 1., 2.])

In [6]:
ft.squeeze(dim = 0).shape

torch.Size([3, 1])

In [7]:
ft.squeeze(dim = 1).shape

torch.Size([3])

## unsqueeze

In [8]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [9]:
ft

tensor([0., 1., 2.])

In [10]:
# dim =0으로 한 것과 동일

print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [11]:
# 위와 동일
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [12]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [13]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [14]:
print(ft.unsqueeze(-2))
print(ft.unsqueeze(-2).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [15]:
print(ft.unsqueeze(1).unsqueeze(1))
print(ft.unsqueeze(1).unsqueeze(1).shape)

tensor([[[0.]],

        [[1.]],

        [[2.]]])
torch.Size([3, 1, 1])


### squeeze, unsqueeze 함수에서 인자에 숫자는 dim = x 이며, x 차원에 1을 없애고 넣는 것

### ex. .squeeze(dim = 1) 이면 차원의 인덱스 1 자리에 숫자를 1을 없애는 것

### ex. .unsqueeze(dim = 1) 이면 차원의 인덱스 1 자리에 숫자를 1을 추가하는 것

## Type Casting

In [16]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [17]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [18]:
bt = torch.ByteTensor( [True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [19]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [20]:
bt2 = (lt == 3)
bt2

tensor([False, False,  True, False])

## Concatenate

In [21]:
x = torch.FloatTensor( [ [1,2], [3,4] ])
y = torch.FloatTensor( [ [5,6], [7,8] ])

In [22]:
x.shape, y.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [23]:
xy0 = torch.cat([x,y], dim = 0)
xy1 = torch.cat([x,y], dim = 1)
print(xy0)
print(xy1)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [24]:
xy0.shape, xy1.shape

(torch.Size([4, 2]), torch.Size([2, 4]))

## Stacking

In [25]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [26]:
x.shape, y.shape, z.shape

(torch.Size([2]), torch.Size([2]), torch.Size([2]))

In [27]:
# default : dim = 0
xyz = torch.stack([x,y,z])
print(xyz)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [28]:
xyz1 = torch.stack([x,y,z], dim = 1)
print(xyz1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [29]:
xyz_us_c = torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)])
print(xyz_us_c)
print()
print(xyz_us_c.shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

torch.Size([3, 2])


In [30]:
x2 = torch.FloatTensor([[1,4], [7,10]])
y2 = torch.FloatTensor([[2,5], [8, 11]])
z2 = torch.FloatTensor([[3,6], [9, 12]])

In [31]:
x2.shape, y2.shape, z2.shape

(torch.Size([2, 2]), torch.Size([2, 2]), torch.Size([2, 2]))

In [32]:
xyz2_0 = torch.stack([x2,y2,z2], dim = 0)
xyz2_0, xyz2_0.shape

(tensor([[[ 1.,  4.],
          [ 7., 10.]],
 
         [[ 2.,  5.],
          [ 8., 11.]],
 
         [[ 3.,  6.],
          [ 9., 12.]]]),
 torch.Size([3, 2, 2]))

In [33]:
xyz2_1 = torch.stack([x2,y2,z2], dim = 1)
xyz2_1, xyz2_1.shape

(tensor([[[ 1.,  4.],
          [ 2.,  5.],
          [ 3.,  6.]],
 
         [[ 7., 10.],
          [ 8., 11.],
          [ 9., 12.]]]),
 torch.Size([2, 3, 2]))

In [34]:
xyz2_2 = torch.stack([x2,y2,z2], dim = 2)
xyz2_2

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [35]:
xyz2_2.shape

torch.Size([2, 2, 3])

### stack은 dim 에서 쌓는 것

## Ones & Zeros

In [36]:
x = torch.FloatTensor([ [0,1,2], [2,1,0]])
print(x, x.shape)

tensor([[0., 1., 2.],
        [2., 1., 0.]]) torch.Size([2, 3])


In [37]:
# x와 같은 dim에 1, 0으로 채워진 것을 반환
torch.ones_like(x), torch.zeros_like(x)

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

## In-place Operation

In [38]:
x = torch.FloatTensor([[1,2], [3,4]])
x, x.shape

(tensor([[1., 2.],
         [3., 4.]]),
 torch.Size([2, 2]))

In [39]:
x.mul(2.), x

(tensor([[2., 4.],
         [6., 8.]]),
 tensor([[1., 2.],
         [3., 4.]]))

In [40]:
x.mul_(2.), x

(tensor([[2., 4.],
         [6., 8.]]),
 tensor([[2., 4.],
         [6., 8.]]))

### _가  없으면 원 변수는 바뀌지 않고 (Call by value)
### _가 있으면  원 변수가 바로 바뀜 (Call by reference)
=> 용어가 기억 안나네 저런 함수들을 가리키는 용어 있는데...